apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret
  namespace: wordpress

type: Opaque

# Las variables de entorno que necesita MySQL para crear la base de datos y el usuario
# las definimos en un Secret de Kubernetes para que no se vean en el manifiesto del Deployment ni en el Pod.
# si fuese de tipo data, deberíamos codificar en base64 los valores de las variables, pero con stringData podemos 
# ponerlas en texto plano y Kubernetes se encarga de codificarlas.
# Nota: Para codificar un texto usar : echo -n "mi_texto" | base64
stringData:
  MYSQL_ROOT_PASSWORD: Password1234
  # nombre de la base de datos
  MYSQL_DATABASE: wordpress

  #usuario de la base de datos
  MYSQL_USER: wordpress
  MYSQL_PASSWORD: wordpresspassword