apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql
  namespace: wordpress

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:

      - name: mysql
        image: mysql:8.4

        ports:
        - containerPort: 3306

        envFrom:
        # indicamos que las variables de entorno que necesita MySQL para crear la base de datos y el usuario se obtendrán del 'mysql-secret.yaml'
        - secretRef:
            name: mysql-secret
        # volumen persistente para almacenar los datos de MySQL
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc