apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: wordpress-pvc
  namespace: wordpress

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: managed-csi

  resources:
    requests:
      storage: 10Gi