apiVersion: v1
kind: Service

metadata:
  name: wordpress
  namespace: wordpress

spec:
  selector:
    app: wordpress

  ports:
  - port: 80
    targetPort: 80

  # Azure nos creará la IP pública
  type: LoadBalancer